function HisDB = HisFutureData(DB,windcode,Options)
I = DB.CurrentK;
HisDB = DB;
HisDB.Times = HisDB.Times(1:I,:);
HisDB.TimesStr = HisDB.TimesStr(1:I,:);
HisDB.NK = length(HisDB.Times);
for i=1:max(size(windcode))
    stock = windcode{i};
    structName = code2structname(stock,'F');
    Data=getfield(HisDB,structName);
    Data.Times = Data.Times(1:I,:);
    Data.TimesStr = Data.TimesStr(1:I,:);
    Data.Sec_status = Data.Sec_status(1:I,:);
    Data.Pct_chg = Data.Pct_chg(1:I,:);
    Data.chg = Data.chg(1:I,:);
    Data.Open = Data.Open(1:I,:);
    Data.High = Data.High(1:I,:);
    Data.Low = Data.Low(1:I,:);
    Data.Close = Data.Close(1:I,:);
    Data.Volume = Data.Volume(1:I,:);
    Data.Vwap = Data.Vwap(1:I,:);
    Data.Settle = Data.Settle(1:I,:);
    Data.PreSettle = Data.PreSettle(1:I,:);
    HisDB=setfield(HisDB,structName,Data);
end